name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/android

      - name: Build Web Assets
        # Ensure www directory exists and has content (vanilla JS project)
        run: |
          if [ ! -d "www" ]; then
            echo "Creating www directory..."
            mkdir -p www
            cp index.html www/
            cp -r css js icons manifest.json sw.js www/
          fi
          # If screenshots exist, copy them too
          if [ -d "screenshots" ]; then
             mkdir -p www/screenshots
             cp screenshots/* www/screenshots/
          fi

      - name: Setup Android Platform
        run: |
          if [ ! -d "android" ]; then
            echo "Android folder missing, adding platform..."
            npx cap add android
          else
            echo "Android folder exists, syncing..."
            npx cap sync android
          fi

      - name: Build APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: expense-tracker-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
